# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.0)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS OsterLib::bytes OsterLib::serial OsterLib::lineNoise OsterLib::CLInput OsterLib::compressor OsterLib::boost_functional OsterLib::images OsterLib::types OsterLib::utilities)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target OsterLib::bytes
add_library(OsterLib::bytes INTERFACE IMPORTED)

set_target_properties(OsterLib::bytes PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include"
)

# Create imported target OsterLib::serial
add_library(OsterLib::serial INTERFACE IMPORTED)

set_target_properties(OsterLib::serial PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include"
  INTERFACE_LINK_LIBRARIES "OsterLib::bytes"
)

# Create imported target OsterLib::lineNoise
add_library(OsterLib::lineNoise STATIC IMPORTED)

set_target_properties(OsterLib::lineNoise PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/linenoise"
)

# Create imported target OsterLib::CLInput
add_library(OsterLib::CLInput STATIC IMPORTED)

set_target_properties(OsterLib::CLInput PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:OsterLib::lineNoise>"
)

# Create imported target OsterLib::compressor
add_library(OsterLib::compressor INTERFACE IMPORTED)

set_target_properties(OsterLib::compressor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libz.so"
)

# Create imported target OsterLib::boost_functional
add_library(OsterLib::boost_functional STATIC IMPORTED)

set_target_properties(OsterLib::boost_functional PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include/boost_functional;/home/oster/OsterLib/include/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Boost::json>"
)

# Create imported target OsterLib::images
add_library(OsterLib::images INTERFACE IMPORTED)

set_target_properties(OsterLib::images PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include/images"
  INTERFACE_LINK_LIBRARIES "PNG::PNG"
)

# Create imported target OsterLib::types
add_library(OsterLib::types STATIC IMPORTED)

set_target_properties(OsterLib::types PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include/types;/home/oster/OsterLib/include/"
  INTERFACE_LINK_LIBRARIES "OsterLib::boost_functional"
)

# Create imported target OsterLib::utilities
add_library(OsterLib::utilities STATIC IMPORTED)

set_target_properties(OsterLib::utilities PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/oster/OsterLib/include"
)

# Import target "OsterLib::lineNoise" for configuration "Debug"
set_property(TARGET OsterLib::lineNoise APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OsterLib::lineNoise PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/home/oster/OsterLib/liblineNoise.a"
  )

# Import target "OsterLib::CLInput" for configuration "Debug"
set_property(TARGET OsterLib::CLInput APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OsterLib::CLInput PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/oster/OsterLib/libCLInput.a"
  )

# Import target "OsterLib::boost_functional" for configuration "Debug"
set_property(TARGET OsterLib::boost_functional APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OsterLib::boost_functional PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/oster/OsterLib/libboost_functional.a"
  )

# Import target "OsterLib::types" for configuration "Debug"
set_property(TARGET OsterLib::types APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OsterLib::types PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/oster/OsterLib/libtypes.a"
  )

# Import target "OsterLib::utilities" for configuration "Debug"
set_property(TARGET OsterLib::utilities APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OsterLib::utilities PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/oster/OsterLib/libutilities.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
