add_test([=[TimeSequence.ConstructionTest]=]  /home/oster/OsterLib/tests/time_sequence_test [==[--gtest_filter=TimeSequence.ConstructionTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TimeSequence.ConstructionTest]=]  PROPERTIES DEF_SOURCE_LINE /home/oster/OsterLib/tests/time_sequence.cpp:4 WORKING_DIRECTORY /home/oster/OsterLib/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TimeSequence.MakeFromRangeTest]=]  /home/oster/OsterLib/tests/time_sequence_test [==[--gtest_filter=TimeSequence.MakeFromRangeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TimeSequence.MakeFromRangeTest]=]  PROPERTIES DEF_SOURCE_LINE /home/oster/OsterLib/tests/time_sequence.cpp:26 WORKING_DIRECTORY /home/oster/OsterLib/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TimeSequence.PushTimeTest]=]  /home/oster/OsterLib/tests/time_sequence_test [==[--gtest_filter=TimeSequence.PushTimeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TimeSequence.PushTimeTest]=]  PROPERTIES DEF_SOURCE_LINE /home/oster/OsterLib/tests/time_sequence.cpp:71 WORKING_DIRECTORY /home/oster/OsterLib/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TimeSequence.ExtendableTest]=]  /home/oster/OsterLib/tests/time_sequence_test [==[--gtest_filter=TimeSequence.ExtendableTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TimeSequence.ExtendableTest]=]  PROPERTIES DEF_SOURCE_LINE /home/oster/OsterLib/tests/time_sequence.cpp:87 WORKING_DIRECTORY /home/oster/OsterLib/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TimeSequence.ExtendByIntervalTest]=]  /home/oster/OsterLib/tests/time_sequence_test [==[--gtest_filter=TimeSequence.ExtendByIntervalTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TimeSequence.ExtendByIntervalTest]=]  PROPERTIES DEF_SOURCE_LINE /home/oster/OsterLib/tests/time_sequence.cpp:102 WORKING_DIRECTORY /home/oster/OsterLib/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  time_sequence_test_TESTS TimeSequence.ConstructionTest TimeSequence.MakeFromRangeTest TimeSequence.PushTimeTest TimeSequence.ExtendableTest TimeSequence.ExtendByIntervalTest)
